# Generated by Django 4.1.7 on 2023-03-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='named_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='visible',
        ),
    ]
