# Generated by Django 4.1.7 on 2023-03-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0002_alter_menuitem_options_rename_named_url_menu_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeMenu.menuitem'),
        ),
    ]
