# Generated by Django 4.0.4 on 2023-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0004_rename_url_menu_named_url_remove_menu_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='submenus',
            field=models.ManyToManyField(to='TreeMenu.menu'),
        ),
    ]
