# Generated by Django 4.0.4 on 2023-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0007_remove_menuitem_submenus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='menu',
            name='subcategories',
            field=models.ManyToManyField(to='TreeMenu.menu'),
        ),
    ]
