# Generated by Django 4.0.4 on 2023-03-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0008_remove_menuitem_parent_menu_subcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='subcategories',
            new_name='submenus',
        ),
    ]
