# Generated by Django 4.0.4 on 2023-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0009_rename_subcategories_menu_submenus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='submenus',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='submenus',
            field=models.ManyToManyField(to='TreeMenu.menu'),
        ),
    ]
