# Generated by Django 4.1.7 on 2023-03-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0010_remove_menu_submenus_menuitem_submenus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='submenus',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TreeMenu.menuitem'),
        ),
    ]
