# Generated by Django 4.1.7 on 2023-03-04 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0011_remove_menuitem_submenus_menuitem_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeMenu.menuitem'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
